apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-client
  labels:
    app: kube-client
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-client
      tier: frontend
  template:
    metadata:
      labels:
        app: kube-client
        tier: frontend
    spec:
      containers:
        - name: kube-client
          image: "kube-client:0.1"
          ports:
            - containerPort: 8080
