apiVersion: v1
kind: Service
metadata:
  name: kube-client
  labels:
    app: kube-client
spec:
  selector:
    app: kube-client
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007
